name: "Test on PR"

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Test on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm test
        env:
          CI: true
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          VERIFIED_EMAIL: ${{ secrets.VERIFIED_EMAIL }}
          EMAILS: ${{ secrets.EMAILS }}
          APP_NAME: ${{ secrets.APP_NAME }}
